[package]
name = "mcl-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
mcl-api = { path = "../api" }
serde = "1"
eframe = { version = "0.20", features = ["persistence", "ron"] }
egui = "0.20"

tracing = "0.1"
tracing-subscriber = "0.3"
